### ISSUE TITLE
Clean up the Readme

### ISSUE THREAD

**Issue by natemcintosh** [CDCgov/cfazuR#4]
## Goal
The README currently has all the usual boilerplate from the template. Remove any unnecessary parts, and add in new parts relevant to this repo.

## Context
Ideally, the README should be mostly about this project. At the moment, it's a mix of basics like license, instructions on how to use the template, and placeholders.

## Required features

- Remove the "how to use this template" section
- Fill in the Skeleton that it lays out

## Out of scope

- Anything beyond fixing up the README

## Related documents

- The [MSR](https://github.com/CDCgov/multisignal-epi-inference) has a nice README
- The [GAM Rt](https://github.com/CDCgov/cfa-gam-rt) repo has a nice README

**Comment by kgostic** [comment]
I'm going to start working on this. If we're using Packagedown (https://pkgdown.r-lib.org/articles/pkgdown.html), which I think we should, then the Readme.md will also be the homepage of the package website. This usually contains a "getting started" vignette

**Comment by natemcintosh** [comment]
I already have a branch created, and I think completed, but I just need #9 merged.

**Comment by natemcintosh** [comment]
Ok, I think I somehow accidentally merged the readme updates in the previous [PR](https://github.com/CDCgov/cfazuR/commit/54c4cad2aeac2b65c2f50cf90ad6cab83758224c). Not entirely sure how that happened 😅. Closing this issue.
